import {TWishlist} from "@/entities/wishlist";

export const wishlistsMock: TWishlist[] = [
    {
        id: "1",
        name: "Birthday Wishlist 2024",
        description: "All the things I'm hoping to get for my birthday this year. From books to gadgets!",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2023-08-15'),
        updatedAt: new Date('2024-01-15'),
        isPublic: true,
        ownerId: "u123",
        allowComments: true,
        allowSuggestions: true,
        notifyOnPurchase: true,
    },
    {
        id: "2",
        name: "Home Decor Dreams",
        description: "Beautiful pieces to make our house feel more like home. Focusing on cozy and modern vibes.",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2025-10-05'),
        updatedAt: new Date('2025-11-15'),
        isPublic: false,
        ownerId: "u123",
        allowComments: false,
        allowSuggestions: true,
        notifyOnPurchase: false,
    },
    {
        id: "3",
        name: "Tech Gadgets",
        description: "Latest tech gadgets and accessories that caught my eye. Perfect for productivity and fun!",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2024-01-02'),
        updatedAt: new Date('2024-01-26'),
        isPublic: true,
        ownerId: "3",
        allowComments: true,
        allowSuggestions: false,
        notifyOnPurchase: true,
    },
    {
        id: "4",
        name: "Books to Read",
        description: "A curated list of books I want to read this year. Mix of fiction, non-fiction, and self-help.",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2023-09-22'),
        updatedAt: new Date('2024-01-22'),
        isPublic: false,
        ownerId: "1",
        allowComments: false,
        allowSuggestions: true,
        notifyOnPurchase: true,
    },
    {
        id: "5",
        name: "Fashion Finds",
        description: "Stylish clothing and accessories for the upcoming season. Casual and formal wear included.",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2023-12-10'),
        updatedAt: new Date('2024-01-24'),
        isPublic: true,
        ownerId: "4",
        allowComments: true,
        allowSuggestions: true,
        notifyOnPurchase: false,
    },
    {
        id: "6",
        name: "Gaming Setup",
        description: "Upgrading my gaming rig with new peripherals and accessories.",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2023-10-15'),
        updatedAt: new Date('2024-01-27'),
        isPublic: true,
        ownerId: "3",
        allowComments: false,
        allowSuggestions: true,
        notifyOnPurchase: true,
    },
    {
        id: "7",
        name: "Travel Essentials",
        description: "Gear for my next adventure, focusing on lightweight and durable items.",
        coverImage: "/placeholder.svg?height=200&width=300",
        createdAt: new Date('2025-01-15'),
        updatedAt: new Date('2025-01-25'),
        isPublic: false,
        ownerId: "5",
        allowComments: true,
        allowSuggestions: false,
        notifyOnPurchase: true,
    },
]